In [2]:
pip install numpy

You should consider upgrading via the 'c:\users\swati rao\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


# Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np


arr = np.zeros(10,dtype = int)
arr[4] = 1

print(arr)

[0 0 0 0 1 0 0 0 0 0]


# 2. Create a vector with values ranging from 10 to 49.

In [2]:
array_1 = np.arange(10,50)

array_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
array_2 = np.arange(0,9).reshape(3,3)

print(array_2)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
n_array = np.array([1,2,0,0,4,0])

print("Original array:")
print(n_array)

# np.nonzero()
print("\nIndices of null elements:")

res = np.nonzero(n_array == 0)
print(res)

Original array:
[1 2 0 0 4 0]

Indices of null elements:
(array([2, 3, 5], dtype=int64),)


# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [5]:
n_array = np.random.random((10,10))

print("the original array",n_array)

print("\n\n")
print("the minimum value of n_array: \n",n_array.min())
      
print("\n\n")
print("the maximun value of n_array: \n",n_array.max())

the original array [[0.41102442 0.33741373 0.10868686 0.31470667 0.12436593 0.62311572
  0.32347012 0.27959797 0.39085638 0.31585159]
 [0.96067255 0.05492936 0.81709592 0.4639806  0.83664361 0.91580296
  0.8933716  0.33740103 0.38707534 0.24690202]
 [0.54746711 0.06877056 0.0673731  0.30096642 0.05597973 0.37906266
  0.69298746 0.5956099  0.47128443 0.60367401]
 [0.3737498  0.14065542 0.52627254 0.49872994 0.41106766 0.58771281
  0.3323124  0.34142466 0.73400143 0.19444909]
 [0.62250406 0.52574188 0.56771551 0.82428191 0.84520464 0.09796136
  0.47836763 0.84116639 0.76887342 0.66221966]
 [0.91822108 0.06199337 0.40484223 0.87690933 0.84265066 0.85755635
  0.58988847 0.86833171 0.88387317 0.08203778]
 [0.37416273 0.03484103 0.19354263 0.67354804 0.92311035 0.32583612
  0.60115116 0.67313636 0.95438989 0.94136495]
 [0.77733713 0.05386924 0.62943553 0.71823023 0.42214129 0.68922506
  0.49657176 0.96701641 0.68719246 0.74769863]
 [0.51883304 0.03824171 0.0701817  0.02490159 0.37989584 0.80

# 6. Create a random vector of size 30 and find the mean value.

In [6]:
import numpy as np

z = np.random.random(30)
print("the random array is: \n",z)

mean_1 = z.mean()
print("\n\nthe mean value of array: \n ",mean_1)

the random array is: 
 [0.0884764  0.43644601 0.67407189 0.39677537 0.32251161 0.93009299
 0.06067572 0.62132808 0.54445602 0.07931826 0.41548733 0.02576902
 0.41139684 0.40437236 0.40702569 0.1828397  0.01417571 0.76505948
 0.47597295 0.39195878 0.46581036 0.88193332 0.48429612 0.86205773
 0.56266172 0.64453372 0.94636937 0.02213184 0.78438563 0.53378881]


the mean value of array: 
  0.4612059611271024
